//
// Created by Usuario on 12/09/2022.
//

#ifndef PROYECTOLENGUAJESPROGRAMACION_OUTPUT_H
#define PROYECTOLENGUAJESPROGRAMACION_OUTPUT_H


class Output {
public:
    void menu();
};


#endif //PROYECTOLENGUAJESPROGRAMACION_OUTPUT_H
